# Generated by Django 4.1.5 on 2023-01-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_product_alter_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='products',
        ),
    ]
