# Generated by Django 4.1.5 on 2023-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
