# Generated by Django 4.1.5 on 2023-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
